# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
pr:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    npm test
  displayName: 'Test'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'webhint-staging'
    appType: 'functionAppLinux'
    appName: 'webhint-staging-functions'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOCKER|microsoft/azure-functions-node8:2.0'